enviando tarea-7
sergio-ceballos-intelex/tareas-modulo-3-grupo-10 pull request #74
Opened 2024-08-11 22:00 UTC by carlanga2025

2024-08-12 04:36 UTC, sergio-ceballos-intelex commented on carlos-portilla-946193746/tarea-7/punto1.js
> +const productosConStock = productos.filter((producto) => producto.stock !== 0);
que pasa si ingresan por accidente un numero negativo?

2024-08-12 04:39 UTC, sergio-ceballos-intelex commented on carlos-portilla-946193746/tarea-7/punto1.js
> +    sumaPrecioTotal += productos[i].precio;
aqui estas calculando la suma total sin verificar si esta en stock o no

2024-08-12 04:41 UTC, sergio-ceballos-intelex requested changes
corregir comentarios

2024-08-12 21:15 UTC, carlanga2025 commented on carlos-portilla-946193746/tarea-7/punto1.js
> +    sumaPrecioTotal += productos[i].precio;
![correccion punto-1-tarea-7](https://github.com/user-attachments/assets/8466dde6-e8ba-4211-aaab-8ca2cd39bb93)
correccion

2024-08-14 14:20 UTC, sergio-ceballos-intelex approved these changes

2024-08-14 14:20 UTC, merged