Tarea 7
sergio-ceballos-intelex/tareas-modulo-3-grupo-10 pull request #88
Opened 2024-08-14 23:53 UTC by JorgeArenas85

![image](https://github.com/user-attachments/assets/4d50f3d2-5431-4562-a0c0-ecc1ac18cfde)
![Captura de pantalla 2024-08-14 173604](https://github.com/user-attachments/assets/c1b21545-43cb-4e5f-bc0d-f407018fd669)
![Captura de pantalla 2024-08-14 175814](https://github.com/user-attachments/assets/9fd48625-3ec9-4a95-aeb4-bf57483b7461)
![Captura de pantalla 2024-08-14 182459](https://github.com/user-attachments/assets/e2d9a885-302c-4b6d-a246-7eac1676b4d0)
![Captura de pantalla 2024-08-14 183226](https://github.com/user-attachments/assets/473cdd31-8c70-46a0-a55e-e59f1a25e34e)
![Captura de pantalla 2024-08-14 183627](https://github.com/user-attachments/assets/46543d18-c8b4-4ae4-adad-f4fdd52415a9)
![Captura de pantalla 2024-08-14 184104](https://github.com/user-attachments/assets/58d97b45-068d-435f-aac9-3d7ce9e132a9)

2024-08-14 23:54 UTC, JorgeArenas85 commented
Cordial saludo profesor adjunto tarea N°7 quedo atento a cualquier retroalimentación

2024-08-18 21:26 UTC, sergio-ceballos-intelex requested changes
la tarea esta bien pero elimina esa carpeta rara que se llama tareas-modulo-3-grupo-10

2024-08-22 03:00 UTC, sergio-ceballos-intelex approved these changes

2024-08-22 03:00 UTC, sergio-ceballos-intelex approved these changes

2024-08-22 03:00 UTC, merged