Agregada nueva funcionalidad
sergio-ceballos-intelex/tareas-modulo-3-grupo-10 pull request #9
Opened 2024-07-27 01:32 UTC by JonnyLunaG

2024-07-27 01:32 UTC, JonnyLunaG commented
subo tarea 2

2024-07-27 01:33 UTC, JonnyLunaG commented
hago entrega tarea 2

2024-07-27 01:58 UTC, sergio-ceballos-intelex requested changes
te falto crear la carpeta tarea-2

2024-07-30 01:44 UTC, sergio-ceballos-intelex approved these changes

2024-07-30 01:44 UTC, merged